HomeRental_System/HomeRentalSystem/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homerental.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HomeRental_System/homerental/urls.py
from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path('',views.home,name='home'),
    path('user/account/', views.user_account, name='user_account'),
    path('user/login/', views.user_login, name='user_login'),
    path('user/register/', views.register, name='register'),
    path('Adds/<str:pk>/', views.Add, name='add'),
    path('user/logout/', views.user_logout, name='user_logout'),
    path('user/account/update-profile/', views.update_account, name='update_profile'),
    path('create-homeAdd/', views.create_homeAdd, name='create_homeAdd'),
    path('update-homeAdd/<str:pk>/', views.update_add, name='update-add'),
    path('delete-homeAdd/<str:pk>/', views.delete_add, name='delete-add'),
    path('user/<str:pk>/', views.user_profile, name='user_profile'),
    path('inbox/', views.inbox, name='inbox'),
    path('inbox/settings/', views.notificatoinSettings, name='notificationSettings'),
    path('user/notification', views.createHomeAddNotification, name='addNotification'),
    path('user/notification_update/<str:pk>/', views.update_notification, name='updateNotification'),
    path('user/delete-notification/<str:pk>/', views.delete_notification, name='delete_notification'),
    path('user/message/<str:pk>/', views.readmessage, name='readmessage'),
    path('user/sendmessage/<str:pk>/', views.sendmessage, name='sendmessage'),
    path('user/complain/<str:pk>/', views.complain, name='complain')
]

HomeRental_System/homerental/models.py
import uuid

from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, unique=True)
    profile_image = models.ImageField(null=True, blank=True, upload_to='profile/', default='profile/user-default.png')
    social_facebook = models.CharField(max_length=200, null=True, blank=True)
    location = models.CharField(max_length=500,null=True,blank=True)
    phone = models.CharField(max_length=11,null=True,blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    is_homeowner = models.BooleanField(default=False)

    def __str__(self):
        return str(self.name)

class HomeOwner(models.Model):
    user_profile = models.OneToOneField(Profile, on_delete=models.CASCADE)
   # renters = models.ForeignKey(Renter, on_delete=None, null=True, blank=True)

    def __str__(self):
       return str(self.user_profile.name)


class Renter(models.Model):
    user_profile = models.OneToOneField(Profile, on_delete=models.CASCADE)
   #homeOwner = models.OneToOneField('HomeOwner', on_delete=None, null=True, blank=True)
    homeOwner = models.ForeignKey(HomeOwner, on_delete=models.SET_NULL, null=True, blank=True)




class HomeAdd(models.Model):
    home_type = (
        ('apartment', 'apartment'),
        ('room', 'room')
    )
    home_owner = models.ForeignKey(HomeOwner, on_delete=models.CASCADE)
    renter = models.OneToOneField(Renter, on_delete=models.SET_NULL, null=True, blank=True)
    block_name = models.CharField(max_length=1)
    road_num = models.CharField(max_length=3)
    house_num = models.CharField(max_length=5)
    house_details = models.CharField(max_length=1000)
    house_type = models.CharField(max_length=20, choices=home_type)



class HomeImages(models.Model):
    home = models.ForeignKey(HomeAdd,on_delete=models.CASCADE,null=True,blank=True)
    image = models.ImageField(null=True, blank=True, default="default.jpg")


class Message(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    reciver = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name='messages')
    body = models.TextField()
    is_read = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return str(self.body[:30])

    class Meta:
        ordering = ['is_read', '-created']

class Complain(models.Model):
    complainer = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name='complainer')
    complainee = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name='complainee')
    complain = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


class AddNoticifation(models.Model):
    renter = models.ForeignKey(Renter, on_delete=models.CASCADE, related_name='notific')
    block_name = models.CharField(max_length=1, null=False)
    road_number = models.IntegerField(null=True, blank=True, default=0)
    maximum_rent_ammount = models.FloatField(default=0)
    created = models.DateTimeField(auto_now_add=True,null=True)
    class Meta:
        ordering = ['-created']


HomeRental_System/homerental/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from . import models
from . import forms

# Create your views here.


def home(request):
       q = ''
    if request.GET.get('q'):
        q = request.GET.get('q')
    # if request.GET.get('max'):
    #     print('maxx:', request.GET.get('max'))
    all_adds = models.HomeAdd.objects.distinct().filter(
        Q(block_name__icontains=q) | Q(road_num__icontains=q) | Q(house_type__iexact=q))
    max = 1000000
    min = 0
    if request.GET.get('max'):
        max = request.GET.get('max')
        print(max)
    if request.GET.get('min'):
        min = request.GET.get('min')
        print(min)
    try:
        all_adds = all_adds.filter(rent_ammount__lte=max, rent_ammount__gte=min)
        print(all_adds)
    except:
        pass
    return render(request, 'homerental/adds.html', {'title': 'home page', 'adds': all_adds})



# Create your views here.

def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        try:
            user = models.User.objects.get(username=username)

        except:
            messages.error(request, 'user not found')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, 'user successfully logged in')
            return redirect(request.GET['next'] if 'next' in request.GET
                            else 'user_account')
        else:
            messages.error(request, 'username or password incorrect')

    return render(request, 'homerental/login_register.html')


def register(request):
    form = forms.UserRegisterForm()
    if request.method == 'POST':
        print(request.POST['Sign_UP_as_a_home_owner'])

        try:
            models.Profile.objects.get(email=request.POST['email'])
            messages.error(request, 'Email already exist')

        except:
            form = forms.UserRegisterForm(request.POST)
            if form.is_valid():
                user = form.save(commit=False)
                user.username = user.username.lower()
                user.save()
                print("cheking checking")
                homeowner=False
                if request.POST['Sign_UP_as_a_home_owner']:
                    print("true")
                    homeowner =True
                else:
                    print("false")
                    homeowner=False

                new_profile = models.Profile.objects.create(
                    user=user,
                    email=user.email,
                    name=user.username,
                    is_homeowner=homeowner
                )

                if(homeowner):
                    models.HomeOwner.objects.create(user_profile=new_profile)
                else:
                    models.Renter.objects.create(user_profile=new_profile)


                login(request, user)
                messages.success(request, 'user account was created')
                return redirect('user_account')

            else:
                messages.error(request, 'error occurred')

    page = 'register'
    context = {'page': page, 'form': form}
    return render(request, 'homerental/login_register.html', context)


@login_required(login_url='user_login')
def user_logout(request):
    logout(request)
    messages.info(request, 'user succesfully logged out')

@login_required(login_url='user_login')
def user_account(request):
    user = request.user
    context = {'user': user}
    return render(request, 'homerental/account.html', context)

@login_required(login_url='user_login')
def update_profile(request):
    profile = request.user.profile

    if request.method == 'POST':
        profile_form = forms.UserUpdateForm(request.POST, request.FILES, instance=profile)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'profile updated successfully')
            return redirect('user_account')

    profile_form = forms.UserUpdateForm(instance=profile)
    context = {'profile_form': profile_form}
    return render(request, 'homerental/update_profile.html', context)

@login_required(login_url='user_login')
def create_homeAdd(request):
    homeadd_form = None
    if request.method == 'POST':

        homeadd_form = forms.HomeAddForm(request.POST, request.FILES)
        if homeadd_form.is_valid():
            add = homeadd_form.save(commit=False)
            add.home_owner = request.user.profile.homeowner
            homeadd_form.save()
            messages.success(request, 'Home add added successfully')
            images = request.FILES.getlist('image')
            for image in images:
                models.HomeImages.objects.create(home=add,image=image)


            return redirect('user_account')

    add_form = forms.HomeAddForm()
    images_form = forms.ImageForm()
    context = {'add_form': add_form,'images_form':images_form}
    return render(request, 'homerental/homeaddform.html', context)



@login_required(login_url='user_login')
def update_add(request, pk):
    project = models.HomeAdd.objects.get(id=pk)
    Add_form = None
    if request.method == 'POST':
        Add_form = forms.HomeAddForm(request.POST, request.FILES, instance=project)
        if Add_form.is_valid():
            Add_form.save()
            messages.success(request, 'ADD updated successfully')
            return redirect('user_account')

    Add_form = forms.HomeAddForm(instance=project)
    context = {'Add_form': Add_form}
    return render(request, 'homerental/project_form.html', context)


@login_required(login_url='user_login')
def delete_add(request, pk):
    add = models.HomeAdd.objects.get(id=pk)

    if request.method == 'POST':
        add.delete()
        messages.success(request, 'project deleted successfully')
        return redirect('user_account')

    context = {'object': add}
    return render(request, 'delete_template.html', context)


@login_required(login_url='user_login')
def createHomeAddNotification(request):
    notification_form = None
    if request.method == 'POST':
        notification_form = forms.NotificationForm(request.POST)
        if notification_form.is_valid():
            notification = notification_form.save(commit=False)
            notification.renter = request.user.profile.renter
            notification_form.save()
            messages.success(request, 'notifination added successfully')
            return redirect('user_account')

    notification_form = forms.NotificationForm()
    return render(request, 'homerental/notification_form.html', {'notification_form': notification_form})


@login_required(login_url='user_login')
def update_notification(request, pk):
    notification_form = None
    notification = models.AddNoticifation.objects.get(id=pk)
    print(notification.renter)

    if request.method == 'POST':
        notification_form = forms.NotificationForm(request.POST, instance=notification)
        if notification_form.is_valid():
            notification_form.save()
            messages.success(request, 'notification updated successfully')
            return redirect('user_account')

    notification_form = forms.NotificationForm(instance=notification)
    context = {'notification_form': notification_form}
    return render(request, 'homerental/notification_form.html', context)


@login_required(login_url='user_login')
def delete_notification(request, pk):
    notification = models.AddNoticifation.objects.get(id=pk)

    if request.method == 'POST':
        notification.delete()
        messages.success(request, 'notification  deleted successfully')
        return redirect('user_account')

    context = {'object': notification}
    return render(request, 'delete_template.html', context)


@login_required(login_url='user_login')
def delete_add(request, pk):
    add = models.HomeAdd.objects.get(id=pk)

    if request.method == 'POST':
        add.delete()
        messages.success(request, 'project deleted successfully')
        return redirect('user_account')

    context = {'object': add}
    return render(request, 'delete_template.html', context)


@login_required(login_url='user_login')
def inbox(request):
    user_messages = request.user.profile.messages.all()
    context = {'user_messages': user_messages, 'unread_massages': user_messages.filter(is_read=False).count()}
    return render(request, 'homerental/inbox.html', context)


@login_required(login_url='user_login')
def readmessage(request, pk):
    message = request.user.profile.messages.get(id=pk)
    if not message.is_read:
        message.is_read = True
        message.save()
    context = {'message': message}
    return render(request, 'homerental/message.html', context)


def sendmessage(request, pk):
    form = forms.MassegeForm()
    reciver = models.Profile.objects.get(id=pk)

    try:
        sender = request.user.profile
    except:
        sender = None
    if request.method == 'POST':
        form = forms.MassegeForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.sender = sender
            message.reciver = reciver

            if sender:
                message.name = sender.name
                message.email = sender.email
            message.save()

HomeRental_System/homerental/templates/homerental/account.html
<!DOCTYPE html>
<html lang="en">

{% extends 'base.html' %}
{% block content %}
  <!-- Main Section -->
  <main class="settingsPage profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
{#              <a class="tag tag--pill tag--main settings__btn" href="{% url 'update_profile'  %}"><i class="im im-edit"></i> Edit</a>#}
              <img class="avatar avatar--xl dev__avatar" src="{{ user.profile.profile_image.url }}" />
              <h2 class="dev__name">{{ user.profile.name }}</h2>

              <p class="dev__location">{{user.profile.location}}</p>
              <p class="dev__location">{{user.profile.email}}</p>
             <p class="dev__location">{{user.profile.phone}}</p>
               <ul class="dev__social">
                  {% if user.profile.social_facebook %}
                <li>
                  <a title="Facebook" href="{{user.profile.social_facebook}}" target="_blank"><i class="im im-facebook"></i></a>
                </li>
                 {% endif %}
              </ul>
            </div>
          </div>
        </div>
        <div class="column column--2of3">



          <div class="settings">
            <h3 class="settings__title">MY Adds</h3>
{#            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-project' %}"><i class="im im-plus"></i> Add Project</a>#}
          </div>

          <table class="settings__table">
hello
        {% for adds in user.profile.homeowner.homeadd_set.all %}
            <tr>
              <td class="settings__thumbnail">
{#                <a href="single-project.html"><img src="images/project-b.png" alt="Project Thumbnail" /></a>#}
              </td>
              <td class="settings__tableInfo">
                <a href="single-project.html">DevSearch Website UI Design</a>
                <p>
                  Consectetur adipisicing elit. Natus nam dolore aut sed vitae eos architecto unde tempore
                  exercitationem fugiat?...
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
              {% endfor %}
          </table>
        </div>
      </div>
    </div>


  </main>




{% endblock content %}

HomeRental_System/homerental/templates/homerental/adds.html
{% extends 'base.html' %}
{% block content %}
  <!-- Main Section -->
  <main class="projects">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>Search Your Next <span>Home</span></h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search By Projects </label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by block or road" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="projectsList">
      <div class="container">
        <div class="grid grid--three">
          <div class="column">
            <div class="card project">
              <a href="single-project.html" class="project">
                <img class="project__thumbnail" src="images/project-a.png" alt="project thumbnail" />
                <div class="card__body">
                  <h3 class="project__title">Yoga Studio Landing Page Website and Design</h3>
                  <p><a class="project__author" href="profile.html">By Dennis Ivanov</a></p>
                  <p class="project--rating">
                    <span style="font-weight: bold;">98%</span> Postitive
                    Feedback (72 Votes)
                  </p>
                  <div class="project__tags">
                    <span class="tag tag--pill tag--main">
                      <small>NextJS</small>
                    </span>
                    <span class="tag tag--pill tag--main">
                      <small>GraphQL</small>
                    </span>
                    <span class="tag tag--pill tag--main">
                      <small>TypeScript</small>
                    </span>
                  </div>
                </div>
              </a>
            </div>
          </div>

          <div class="column">
            <div class="card project">
              <a href="single-project.html" class="project">
                <img class="project__thumbnail" src="images/project-b.png" alt="project thumbnail" />
                <div class="card__body">
                  <h3 class="project__title">DevSearch UI Design</h3>
                  <p><a class="project__author" href="profile.html">By Shahriar P. Shuvo</a></p>
                  <p class="project--rating">
                    <span style="font-weight: bold;">92%</span> Postitive
                    Feedback (62 Votes)
                  </p>
                  <div class="project__tags">
                    <span class="tag tag--pill tag--main">
                      <small>NextJS</small>
                    </span>
                    <span class="tag tag--pill tag--main">
                      <small>GraphQL</small>
                    </span>
                    <span class="tag tag--pill tag--main">
                      <small>TypeScript</small>
                    </span>
                  </div>
                </div>
              </a>
            </div>
          </div>

          <div class="column">
            <div class="card project">
              <a href="single-project.html" class="project">
                <img class="project__thumbnail" src="images/project-c.png" alt="project thumbnail" />
                <div class="card__body">
                  <h3 class="project__title">Another Landing Page</h3>
                  <p><a class="project__author" href="profile.html">By Dennis Ivanov</a></p>
                  <p class="project--rating">
                    <span style="font-weight: bold;">36%</span> Postitive
                    Feedback (18 Votes)
                  </p>
                  <div class="project__tags">
                    <span class="tag tag--pill tag--main">
                      <small>NextJS</small>
                    </span>
                    <span class="tag tag--pill tag--main">
                      <small>GraphQL</small>
                    </span>
                    <span class="tag tag--pill tag--main">
                      <small>TypeScript</small>
                    </span>
                  </div>
                </div>
              </a>
            </div>
          </div>

          <div class="column">
            <div class="card project">
              <a href="single-project.html" class="project">
                <img class="project__thumbnail" src="images/project-a.png" alt="project thumbnail" />
                <div class="card__body">
                  <h3 class="project__title">Yoga Studio Landing Page Website and Design</h3>
                  <p><a class="project__author" href="profile.html">By Dennis Ivanov</a></p>
                  <p class="project--rating">
                    <span style="font-weight: bold;">98%</span> Postitive
                    Feedback (72 Votes)
                  </p>
                  <div class="project__tags">
                    <span class="tag tag--pill tag--main">
                      <small>NextJS</small>
                    </span>
                    <span class="tag tag--pill tag--main">
                      <small>GraphQL</small>
                    </span>
                    <span class="tag tag--pill tag--main">
                      <small>TypeScript</small>
                    </span>
                  </div>
                </div>
              </a>
            </div>
          </div>

          <div class="column">
            <div class="card project">
              <a href="single-project.html" class="project">
                <img class="project__thumbnail" src="images/project-b.png" alt="project thumbnail" />
                <div class="card__body">
                  <h3 class="project__title">DevSearch UI Design</h3>
                  <p><a class="project__author" href="profile.html">By Shahriar P. Shuvo</a></p>
                  <p class="project--rating">
                    <span style="font-weight: bold;">92%</span> Postitive
                    Feedback (62 Votes)
                  </p>
                  <div class="project__tags">
                    <span class="tag tag--pill tag--main">
                      <small>NextJS</small>
                    </span>
                    <span class="tag tag--pill tag--main">
                      <small>GraphQL</small>
                    </span>
                    <span class="tag tag--pill tag--main">
                      <small>TypeScript</small>
                    </span>
                  </div>
                </div>
              </a>
            </div>
          </div>

          <div class="column">
            <div class="card project">
              <a href="single-project.html" class="project">
                <img class="project__thumbnail" src="images/project-c.png" alt="project thumbnail" />
                <div class="card__body">
                  <h3 class="project__title">Another Landing Page</h3>
                  <p><a class="project__author" href="profile.html">By Dennis Ivanov</a></p>
                  <p class="project--rating">
                    <span style="font-weight: bold;">36%</span> Postitive
                    Feedback (18 Votes)
                  </p>
                  <div class="project__tags">
                    <span class="tag tag--pill tag--main">
                      <small>NextJS</small>
                    </span>
                    <span class="tag tag--pill tag--main">
                      <small>GraphQL</small>
                    </span>
                    <span class="tag tag--pill tag--main">
                      <small>TypeScript</small>
                    </span>
                  </div>
                </div>
              </a>
            </div>
          </div>

        </div>
      </div>
    </section>

  </main>
{% endblock content %}

HomeRental_System/homerental/templates/homerental/chat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="css/chatbox.css">
    <title>ChatBox</title>
</head>
<body>
    <div class="awrapper">
        <div class="atitle">ChatBox</div>
        <div class="abox">
            <div class="aitem">
                <div class="aicon">
                    <i class="fa fa-user"></i>

                </div>
                <div class="amsg">
                    <h3>Afsara Waziha</h3>
                    <p>How many windows does the room have?</p>
                </div>
            </div>
            <br clear="both">
            <div class="aitem right">
                <div class="amsg">
                    <h3>Mithila </h3>
                    <p>Two windows</p>
                </div>

            </div>
        </div>

        <div class="atyping-area">
            <div class="ainput-field">
                <input type="text" placeholder="Type your message" required>
                <button>Send</button>

            </div>

        </div>

    </div>
</body>
</html>

HomeRental_System/homerental/templates/homerental/complain_box.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="css/complain_box_style.css">
</head>
<body>
    <div class="acomplain-box">
        <p>Leave your Complain</p>
        <form action="#" class="acomplain-form">
            <input type="text" placeholder="Name of the complainer">
            <input type="text" placeholder="Name of the complainee">
            <textarea rows="10" placeholder="Write your complain"></textarea>
            <button type="submit">Post Complain</button>
        </form>

    </div>
</body>
</html>

HomeRental_System/homerental/templates/homerental/homeaddform.html
{% extends 'base.html' %}

{% block content %}

</form>

       <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{{ request.META.HTTP_REFERER }}"><i class="im im-angle-left"></i>Back</a>

                <br>

                <form class="form" method="POST"  enctype="multipart/form-data">
                    {% csrf_token %}

                    {% for field in add_form %}
                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">{{ field.label}} </label>
                        {{ field }}
                    </div>
                    {% endfor %}
{#                 <div class="form__field">#}
{#                        <label for="formInput#text">{{ images_form.image.label}} </label>#}
{#                        {{ images_form.image }}#}
{#                    </div>#}
                 <div class="form-group">
    <label for="note-image">Images</label>
    <input type="file" name="image" class="form-control-file" id="note-image" multiple>
  </div>

                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>

{% endblock %}

HomeRental_System/homerental/templates/homerental/update_profile.html
{% extends 'base.html' %}

{% block content %}

</form>

       <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{{ request.META.HTTP_REFERER }}"><i class="im im-angle-left"></i></a>
                <br>

                <form class="form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% for field in profile_form %}
                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">{{ field.label}} </label>
                        {{ field }}
                    </div>
                    {% endfor %}

                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Update" />
                </form>
            </div>
        </div>
    </main>

{% endblock %}